# Generated by Django 4.1.5 on 2023-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="week",
            field=models.CharField(
                choices=[("WEEK1", "WEEK1"), ("WEEK2", "WEEK2"), ("WEEK3", "WEEK3")],
                default="WEEK1",
                max_length=30,
            ),
        ),
    ]
